/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.nghiencuukhoahoc.UI;

import com.mycompany.nghiencuukhoahoc.menu.MenuItem;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author vankh
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        excute();
    }

    
    private void excute(){
        ImageIcon iconBookmark = new ImageIcon("/img/icon.png");
        MenuItem subMenu1 = new MenuItem(iconBookmark,"Kê Khai",null);
        MenuItem subMenu2 = new MenuItem(iconBookmark,"Trường đã duyệt",null);
        MenuItem subMenu3 = new MenuItem(iconBookmark,"Yêu Cầu Cập Nhật",null);
        MenuItem subMenu4 = new MenuItem(iconBookmark,"Không xác nhận",null);
        MenuItem menuBaiBaoKH = new MenuItem(iconBookmark, "Bài Báo Khoa Học",null,subMenu1,subMenu2,subMenu3,subMenu4);
        MenuItem subMenu11 = new MenuItem(iconBookmark,"Kê Khai",null);
        MenuItem subMenu22 = new MenuItem(iconBookmark,"Trường đã duyệt",null);
        MenuItem subMenu32 = new MenuItem(iconBookmark,"Yêu Cầu Cập Nhật",null);
        MenuItem subMenu42 = new MenuItem(iconBookmark,"Không xác nhận",null);
        MenuItem menuBaocaoKH = new MenuItem(iconBookmark, "Báo Cáo Khoa Học",null,subMenu11,subMenu22,subMenu32,subMenu42);
        MenuItem subMenu12 = new MenuItem(iconBookmark,"Kê Khai",null);
        MenuItem subMenu23 = new MenuItem(iconBookmark,"Trường đã duyệt",null);
        MenuItem subMenu33 = new MenuItem(iconBookmark,"Yêu Cầu Cập Nhật",null);
        MenuItem subMenu43 = new MenuItem(iconBookmark,"Không xác nhận",null);
        MenuItem menuBienSoanSach = new MenuItem(iconBookmark, "Biên Soạn Sách",null,subMenu12,subMenu23,subMenu33,subMenu43);
        MenuItem subMenu13 = new MenuItem(iconBookmark,"Kê Khai",null);
        MenuItem subMenu24 = new MenuItem(iconBookmark,"Trường đã duyệt",null);
        MenuItem subMenu34 = new MenuItem(iconBookmark,"Yêu Cầu Cập Nhật",null);
        MenuItem subMenu44 = new MenuItem(iconBookmark,"Không xác nhận",null);
        MenuItem menuChuyenGiaoKHCN = new MenuItem(iconBookmark, "Chuyển Giao Khoa Học Công Nghệ",null,subMenu13,subMenu24,subMenu34,subMenu44);
        MenuItem subMenu14 = new MenuItem(iconBookmark,"Kê Khai",null);
        MenuItem subMenu25 = new MenuItem(iconBookmark,"Trường đã duyệt",null);
        MenuItem subMenu35 = new MenuItem(iconBookmark,"Yêu Cầu Cập Nhật",null);
        MenuItem subMenu45 = new MenuItem(iconBookmark,"Không xác nhận",null);
        MenuItem menuKhoaHocCongNghe = new MenuItem(iconBookmark, "Nhiệm Vụ Khoa Học Công Nghệ",null,subMenu14,subMenu25,subMenu35,subMenu45);
        MenuItem subMenu15 = new MenuItem(iconBookmark,"Kê Khai",null);
        MenuItem subMenu26 = new MenuItem(iconBookmark,"Trường đã duyệt",null);
        MenuItem subMenu36 = new MenuItem(iconBookmark,"Yêu Cầu Cập Nhật",null);
        MenuItem subMenu46 = new MenuItem(iconBookmark,"Không xác nhận",null);
        MenuItem menuSoHuuTriTue = new MenuItem(iconBookmark, "Sở Hữu Trí Tuệ",null,subMenu15,subMenu26,subMenu36,subMenu46);
        MenuItem subMenu16 = new MenuItem(iconBookmark,"Kê Khai",null);
        MenuItem subMenu27 = new MenuItem(iconBookmark,"Trường đã duyệt",null);
        MenuItem subMenu37 = new MenuItem(iconBookmark,"Yêu Cầu Cập Nhật",null);
        MenuItem subMenu47 = new MenuItem(iconBookmark,"Không xác nhận",null);
        MenuItem menuGiaiThuong = new MenuItem(iconBookmark, "Giải Thưởng Khoa Học Công Nghệ",null,subMenu16,subMenu27,subMenu37,subMenu47);
        addMenu(menuBaiBaoKH,menuBaocaoKH,menuBienSoanSach,menuChuyenGiaoKHCN,menuGiaiThuong,menuKhoaHocCongNghe,menuSoHuuTriTue);
    }
    
    private void addMenu(MenuItem... menu){
        for(int i = 0 ; i  < menu.length ; i++){
            menus.add(menu[i]);
            ArrayList<MenuItem> subMenu = menu[i].getsubMenu();
            for(MenuItem m : subMenu){
                addMenu(m);
            }
        }
        menus.revalidate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        scallPanelMenu = new javax.swing.JScrollPane();
        menus = new javax.swing.JPanel();
        panelBody = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelHeader.setBackground(new java.awt.Color(204, 255, 255));
        panelHeader.setPreferredSize(new java.awt.Dimension(521, 50));

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(panelHeader, java.awt.BorderLayout.PAGE_START);

        panelMenu.setBackground(new java.awt.Color(255, 204, 255));
        panelMenu.setPreferredSize(new java.awt.Dimension(300, 388));

        scallPanelMenu.setBorder(null);

        menus.setPreferredSize(new java.awt.Dimension(20, 388));
        menus.setLayout(new javax.swing.BoxLayout(menus, javax.swing.BoxLayout.Y_AXIS));
        scallPanelMenu.setViewportView(menus);

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scallPanelMenu)
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scallPanelMenu)
        );

        getContentPane().add(panelMenu, java.awt.BorderLayout.LINE_START);

        panelBody.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout panelBodyLayout = new javax.swing.GroupLayout(panelBody);
        panelBody.setLayout(panelBodyLayout);
        panelBodyLayout.setHorizontalGroup(
            panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 415, Short.MAX_VALUE)
        );
        panelBodyLayout.setVerticalGroup(
            panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );

        getContentPane().add(panelBody, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(729, 475));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel menus;
    private javax.swing.JPanel panelBody;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JScrollPane scallPanelMenu;
    // End of variables declaration//GEN-END:variables
}
